version: "3.7"

services:
  database:
    image: postgres
    container_name: database_morada
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=morada
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
